name: stomp_dart_client
homepage: https://github.com/blackhorse-one/stomp_dart
version: 0.2.0
description: Dart STOMP client for easy messaging interoperability. Build with flutter in mind, but should work for every dart application.
environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta: ^1.1.7
  web_socket_channel: ^1.1.0

dev_dependencies:
  test: ^1.9.2
  pedantic: ^1.0.0